In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data = '/Users/utsav/Desktop/repos/Pandas-Cookbook-Second-Edition/data/'

In [9]:
movies = pd.read_csv(data + 'movie.csv')
movies.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [6]:
columns = movies.columns
index = movies.index
data = movies.to_numpy()
data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [9]:
type(columns) # pandas.core.indexes.base.Index
type(index)  # pandas.core.indexes.range.RangeIndex
type(data)   # numpy.ndarray

numpy.ndarray

In [10]:
issubclass(pd.RangeIndex, pd.Index) # True == Index --> NumericIndex --> IntegerIndex --> Int64Index -->RangeIndex

True

In [12]:
issubclass(columns.__class__, pd.Index) # True

True

In [13]:
movies.values

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [14]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
m

In [27]:
movies.dtypes.value_counts()
movies['director_name'].value_counts()

Steven Spielberg     26
Woody Allen          22
Clint Eastwood       20
Martin Scorsese      20
Ridley Scott         16
                     ..
Fred Durst            1
Jason Connery         1
Vladlen Barbe         1
Floria Sigismondi     1
Lucky McKee           1
Name: director_name, Length: 2397, dtype: int64

In [28]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   color                      4897 non-null   object 
 1   director_name              4814 non-null   object 
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object 
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object 
 10  actor_1_name               4909 non-null   object 
 11  movie_title                4916 non-null   object 
 12  num_voted_users            4916 non-null   int64  
 13  cast_total_facebook_likes  4916 non-null   int64

In [34]:
pd.Series(['Paul', np.nan, 'George', 10.]).dtypes # dtype('O')

dtype('O')

In [35]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
m

In [43]:
movies.director_name 

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [44]:
movies['director_name']

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [41]:
id(movies.director_name.iloc[4912])

4377252848

In [47]:
movies.loc[:, 'director_name']

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [48]:
movies.iloc[:, 1]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [49]:
type(movies)

pandas.core.frame.DataFrame

In [55]:
movies['director_name'].index # RangeIndex(start=0, stop=4916, step=1)
movies['director_name'].dtype # dtype('O')
movies['director_name'].size  # 4916
movies['director_name'].name  # 'director_name
type(movies['director_name']) # pandas.core.series.Series

pandas.core.series.Series

In [62]:
movies['director_name'].apply(type).unique() # array([<class 'str'>, <class 'float'>], dtype=object)


array([<class 'str'>, <class 'float'>], dtype=object)

In [71]:
s_attr_methods = set(dir(pd.Series))
len(s_attr_methods) # 434

434

In [72]:
df_attr_methods = set(dir(pd.DataFrame))
len(df_attr_methods) # 441

441

In [73]:
len(s_attr_methods & df_attr_methods) # 384

384

In [75]:
director = movies.director_name
fb_likes = movies.actor_1_facebook_likes
director.dtype # dtype('O')
fb_likes.dtype # dtype('float64')

dtype('float64')

In [76]:
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [80]:
director.sample(5, random_state=21)

3568     Claude Chabrol
4056      Monte Hellman
254     Martin Scorsese
3576        Greg Marcks
3021       Lisa Azuelos
Name: director_name, dtype: object

In [81]:
director.value_counts()

Steven Spielberg     26
Woody Allen          22
Clint Eastwood       20
Martin Scorsese      20
Ridley Scott         16
                     ..
Fred Durst            1
Jason Connery         1
Vladlen Barbe         1
Floria Sigismondi     1
Lucky McKee           1
Name: director_name, Length: 2397, dtype: int64

In [82]:
fb_likes.value_counts()

1000.0     436
11000.0    206
2000.0     189
3000.0     150
12000.0    131
          ... 
564.0        1
46000.0      1
49.0         1
447.0        1
161.0        1
Name: actor_1_facebook_likes, Length: 877, dtype: int64

In [100]:
director.size # 4916
type(director.size) # int
director.shape # (4916,)
type(director.shape) # tuple
type(director.unique())

numpy.ndarray

In [101]:
director.unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Scott Smith', 'Benjamin Roberds', 'Daniel Hsia'], dtype=object)

def decor_upper(func):
    def wrapper():
        orig_func = func()
        modified_ver = func().upper() ## Original function is called here
        return modified_ver
    return wrapper

@decor_upper
def greet():
    return 'hello'
@decor_upper
def abuse():
    return 'bastard'

print(greet()) # HELLO
print(abuse()) # BASTARD

# Book - From Python to Numpy

In [3]:
import random
import timeit
class RandomWalker:
    def __init__(self):
        self.position = 0
        
    def walk(self, n):
        self.position = 0
        for i in range(n):
            yield self.position
            self.position += 2 * random.randint(0,1) - 1

walker = RandomWalker()
timeit.Timer('[position for position in walker.walk(10000)]', 'from __main__ import walker').timeit(100)
# 1.418

1.4564085540000065

In [5]:
def walk(n):
    position = 0
    walk = [position]
    for i in range(n):
        position += 2 * random.randint(0,1) - 1
        walk.append(position)
    return walk
timeit.Timer('walk(10000)', 'from __main__ import walk').timeit(100)

1.274039820000013

In [94]:
def random_walk(n=1000):
    steps = np.random.choice([-1,+1], n)
    return np.cumsum(steps)
timeit.Timer('random_walk(10000)', 'from __main__ import random_walk').timeit(100)

0.01899421199959761

In [92]:
np.cumsum(np.random.choice([-1, +1], 10))

array([-1, -2, -1,  0, -1, -2, -3, -4, -3, -2])

In [3]:
%timeit [i*i for i in range(10)]

945 ns ± 4.84 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
import line_profiler
%load_ext line_profiler
%lprun -f walk(1000)

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


/Users/utsav/.conda/envs/myenv/lib/python3.9/site-packages/line_profiler/line_profiler.py:328: UserWarning: Could not extract a code object for the object [0, -1, -2, -1, 0, -1, 0, 1, 2, 3, 2, 1, 2, 3, 4, 3, 4, 3, 2, 3, 2, 3, 2, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, -1, 0, 1, 0, -1, -2, -1, 0, 1, 0, 1, 0, -1, 0, -1, -2, -1, 0, 1, 0, -1, 0, 1, 0, 1, 0, -1, -2, -1, -2, -1, -2, -1, 0, -1, 0, -1, -2, -3, -2, -1, -2, -1, -2, -3, -2, -1, -2, -3, -2, -1, -2, -3, -2, -1, -2, -1, -2, -3, -4, -5, -4, -3, -4, -3, -2, -1, -2, -1, 0, 1, 2, 1, 0, -1, 0, -1, 0, -1, 0, -1, -2, -3, -2, -1, 0, -1, 0, 1, 2, 1, 2, 3, 4, 3, 2, 3, 4, 5, 4, 5, 6, 5, 4, 5, 4, 3, 4, 5, 6, 5, 6, 5, 4, 3, 4, 3, 4, 5, 6, 5, 4, 3, 4, 5, 6, 5, 4, 3, 4, 3, 2, 1, 2, 3, 4, 3, 2, 1, 0, -1, 0, 1, 0, -1, 0, -1, 0, 1, 0, -1, 0, 1, 2, 1, 2, 1, 0, -1, -2, -1, -2, -3, -2, -1, 0, -1, -2, -1, 0, -1, 0, 1, 2, 3, 4, 3, 2, 3, 2, 3, 4, 5, 4, 5, 6, 5, 4, 3, 2, 1, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -10, -11, -10, -11, -12, -1

In [7]:
%lprun -f walk(1000)

/Users/utsav/.conda/envs/myenv/lib/python3.9/site-packages/line_profiler/line_profiler.py:328: UserWarning: Could not extract a code object for the object [0, 1, 0, 1, 2, 1, 0, 1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 1, 2, 1, 0, -1, -2, -1, -2, -3, -4, -5, -6, -7, -8, -9, -8, -9, -8, -9, -8, -7, -6, -5, -6, -7, -8, -7, -6, -5, -4, -3, -2, -3, -4, -5, -4, -5, -4, -5, -6, -5, -4, -3, -2, -3, -4, -5, -6, -5, -6, -7, -6, -5, -6, -7, -6, -7, -8, -7, -6, -5, -4, -5, -6, -7, -8, -7, -8, -7, -8, -9, -10, -11, -10, -11, -10, -11, -10, -11, -10, -9, -10, -11, -12, -11, -10, -11, -12, -11, -12, -11, -10, -11, -10, -9, -8, -7, -6, -7, -6, -5, -4, -5, -4, -3, -2, -1, -2, -1, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, -1, -2, -1, -2, -3, -4, -5, -4, -5, -4, -3, -2, -3, -2, -3, -4, -3, -2, -1, 0, 1, 0, 1, 0, -1, 0, 1, 2, 1, 0, 1, 0, 1, 0, -1, -2, -1, -2, -3, -2, -3, -2, -1, 0, 1, 2, 3, 2, 1, 2, 1, 2, 3, 4, 3, 2, 1, 0, -1, -2, -1, 0, 1, 0, -1, -2, -1, 0, -1, 0, 1, 2, 3, 4, 3, 4, 5, 4, 5, 4, 3, 4, 3, 2, 3, 2, 1, 2, 1,

In [21]:
df = pd.concat([movies, movies, movies])
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [22]:
def f(row):
    row = row + row
    return np.cumsum(row)

In [23]:
%lprun -f f df.apply(lambda row: f(df['duration']))

In [41]:
a = np.arange(20).reshape(5,4)
print(a.ndim) # 2
print(a.shape) # (5,4)
print(a.size) # 20
print(a.dtype) # int64
print(a.itemsize) # 8, size of each item in a array in byte
print(a.data) # 0x126b50520 - Memory location
print(type(a)) # <class 'numpy.ndarray'>

2
(5, 4)
20
int64
8
<class 'numpy.ndarray'>


In [45]:
a = np.array([[1,1,[2,3]], [2,[2,4],3], [[3,1],3,4]], dtype='object')
a.shape # (3, 3)

(3, 3)

In [47]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [49]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [51]:
np.ones((3,3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)