In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold

import matplotlib.pyplot as plt

import pandas as pd
import polars as pl
import numpy as np

In [2]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=.3)

In [4]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [11]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9518518518518518

In [12]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9796296296296296

In [13]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9722222222222222

##### using k fold and stratefied k fold

In [14]:
from sklearn.model_selection import KFold, StratifiedKFold

In [16]:
kf = KFold(n_splits=5)

for train_index, test_index in kf.split(range(1, 10)):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [29]:
score_log_reg = []
score_svm = []
score_random_forest = []

skf = StratifiedKFold(n_splits=10)

for train_index, test_index in skf.split(digits.data, digits.target):
    # X_train, X_test, y_train, y_test = digits.data[train_index], digits.target[test_index], digits.data[train_index], digits.target[test_index]
    # score_log_reg.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    # score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    # score_random_forest.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    print(test_index)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 166 167 168 171 172 173 174 175 177 180 181 188 189 194 198]
[165 169 170 176 178 179 182 183 184 185 186 187 190 191 192 193 195 196
 197 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 2

In [27]:
from sklearn.model_selection import cross_val_score # This internally uses stratified k fold

cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [28]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [30]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [35]:
for n_est in range(5, 51, 5):
    print(cross_val_score(RandomForestClassifier(n_estimators=n_est), digits.data, digits.target))

[0.88888889 0.825      0.89972145 0.88857939 0.83844011]
[0.89722222 0.85555556 0.91364903 0.93314763 0.91086351]
[0.90555556 0.88055556 0.95264624 0.94707521 0.88857939]
[0.93333333 0.90277778 0.9637883  0.95543175 0.90250696]
[0.91666667 0.90833333 0.95264624 0.95821727 0.89972145]
[0.91944444 0.89166667 0.94707521 0.96657382 0.9275766 ]
[0.93333333 0.88055556 0.94150418 0.95543175 0.92200557]
[0.92222222 0.9        0.95264624 0.95543175 0.92200557]
[0.92777778 0.89444444 0.95543175 0.96100279 0.91643454]
[0.93055556 0.90833333 0.9637883  0.95264624 0.93871866]
