In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
data = pd.read_csv('data/2_mul_linreg_homeprices.csv')
data.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
# Data preprocessing
# replace missing bedrooms with median bedroom

median_bedrooms = np.floor(data.bedrooms.median())

In [7]:
data.bedrooms = data.bedrooms.fillna(median_bedrooms)
data.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [12]:
model = linear_model.LinearRegression()
model.fit(data.drop(columns='price'), data.price)


LinearRegression()

In [17]:
model.predict(np.array([3000, 3, 15]).reshape(1, 3))

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

In [18]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
model.intercept_

221323.0018654043

In [20]:
3000*112.062+3*23388.8800+(-3231.718*15)+221323.00

579199.87

### Exercise

In [28]:
df = pd.read_csv('data/2_1_mul_linreg_hiring.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       6 non-null      object 
 1   test_score       7 non-null      float64
 2   interview_score  8 non-null      int64  
 3   salary           8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes


experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [29]:
## data preprocessing
# convert exp to numbers
# fill the missing data

from word2number import w2n
df.experience = df.experience.fillna('zero')
df['experience_num'] = df.experience.apply(w2n.word_to_num)
df.head()

experience  test_score  interview_score  salary  experience_num
0       zero         8.0                9   50000               0
1       zero         8.0                6   45000               0
2       five         6.0                7   60000               5
3        two        10.0               10   65000               2
4      seven         9.0                6   70000               7

In [31]:
df['test_score'] = df.test_score.fillna(np.floor(df.test_score.median()))
df.head()

experience  test_score  interview_score  salary  experience_num
0       zero         8.0                9   50000               0
1       zero         8.0                6   45000               0
2       five         6.0                7   60000               5
3        two        10.0               10   65000               2
4      seven         9.0                6   70000               7

In [32]:
model = linear_model.LinearRegression()
model.fit(df.drop(columns=['experience', 'salary']), df.salary)

LinearRegression()

In [36]:
model.coef_

array([1845.70596798, 2205.24017467, 2812.95487627])

In [37]:
model.intercept_

17737.26346433774

In [42]:
model.predict(np.array([10, 10, 12]).reshape(-1,3))

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])