In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
data = pd.read_csv('data/5_homeprices_onehot.csv')
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [15]:
one_hot_encoded_towns = pd.get_dummies(data.town)
one_hot_encoded_towns.columns = one_hot_encoded_towns.columns.str.replace(' ', '_')
one_hot_encoded_towns

monroe_township  robinsville  west_windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [19]:
final = pd.concat([data, one_hot_encoded_towns], axis=1)
final.head()

town  area   price  monroe_township  robinsville  west_windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [38]:
# removing a one hot encoded column west_windsor ro avoid multicolinearity or dummy variable trap
X = final.drop(columns=['town', 'west_windsor', 'price'])
y = data['price']
X

area  monroe_township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [18]:
model = linear_model.LinearRegression()
model.fit(X, y)

LinearRegression()

In [26]:
# Predict price for west windsor 3450 

model.predict(np.array([3450, 0, 0]).reshape(1, -1))

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([687586.54052891])

In [27]:
# Predict price for monroe township 4400 
model.predict(np.array([4400, 1, 0]).reshape(1, -1))

C:\Users\Utsav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([768125.13437968])

In [28]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [29]:
model.intercept_

249790.36766292527

In [33]:
model.score(X, y)

0.9573929037221872

In [34]:
### Preprocessing data using LabelEncoder and OneHotEncoder from sklearn

In [35]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [37]:
le = LabelEncoder()
dfle = data.copy(deep=True)
dfle['town'] = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [40]:
X = dfle[['town',	'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)